### ISSUE TITLE
Can you share your implementation of MRAC for this work?

### ISSUE THREAD

**Issue by ruturajsambhusvt** [cpezzato/active_inference#2]
Hello,

Very interesting paper and I would like to check out these on the Panda robot I work with. Could you please share the barebone cpp for MRAC implementation as well?

**Comment by cpezzato** [comment]
Hi, 

Thanks! I think what you are looking for is already in the repository, specifically [here](https://github.com/cpezzato/active_inference/blob/50f3b3a62388c288679fa5b3f15cf2b14dfc6d62/franka_custom_controllers/src/MRAC_controller.cpp) .

**Comment by ruturajsambhusvt** [comment]
Hi, thank you for the quick response. I was wondering if you had the one like [this](https://github.com/cpezzato/active_inference/blob/50f3b3a62388c288679fa5b3f15cf2b14dfc6d62/AICpanda.cpp) without ROS. Although, shouldn't be difficult to modify this to MRAC based on the code you pointed to.

**Comment by cpezzato** [comment]
Indeed, I suggest then to just take the two functions related to MRAC at the end of the file and copy paste them into your code or make the examples as for the AIC.
